name: build

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: ['12', '14', '16']

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Linting and check spelling
        run: yarn lint

      - name: Test and collect coverage
        run: yarn test

      - name: Build package
        run: yarn build

      - name: Push coverage to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
